language: ruby
jdk: oraclejdk7
notifications:
  email:
    - levi@leviwilson.com
script:
  - ant units
  - cd cukes
  - bundle install
  - rake
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libstdc++6:i386 lib32z1
  - wget http://dl.google.com/android/android-sdk_r22.3-linux.tgz
  - tar xzf android-sdk_r22.3-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_HOME}/build-tools/19.0.1
  - echo y | android update sdk --filter platform-tools,build-tools-19.0.1,android-15,android-16,sysimg-16,extra-android-support --no-ui --force
  - echo no | android create avd --force -n test -t android-16 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb wait-for-device
